info:
  title: Blog
  author: Chenge XI

defaults:
  avatar: https://avatars.githubusercontent.com/u/157833389?v=4

home:
  sidebar:
    enable: true
    position: left
    first_item: menu

    links:
      Archives: # 显示的名称
        path: /archives # 路径
        icon: fa-regular fa-archive # 图标，可以为空
      Tags: # 显示的名称
        path: /tags # 路径
        icon: fa-regular fa-tags # 图标，可以为空
      Categories: # 显示的名称
        path: /categories # 路径
        icon: fa-regular fa-folder # 图标，可以为空

home_banner:
  enable: true
  static: fixed
  title: HaHa

navbar:
  links:
    Home: # 一级菜单栏名称
      path: / # 网址，可以为相对路径或者绝对路径
      icon: fa-regular fa-house # Fontawesome图标名称（可选）
    Archives:
      path: /archives/
      icon: fa-regular fa-box-archive # Fontawesome图标名称（可选）
    Tag:
      path: /tags/
      icon: fa-solid fa-tag # Fontawesome图标名称（可选）
    Categories: #取名随意
        icon: fa-solid fa-folder #图标
        path: /categories/ #链接
    About:
      path: /about/
      icon: fa-regular fa-address-card # Fontawesome图标名称（可选）

  search:
      # Whether to enable
      enable: true
      # Preload search data when the page loads
      preload: true

global:
  google_analytics:
    enable: true # Whether to enable Google Analytics
    id: G-15HHLVNSFL # Google Analytics Measurement ID
