navbar:
  links:
    Home: # 一级菜单栏名称
      path: / # 网址，可以为相对路径或者绝对路径
      icon: fa-regular fa-house # Fontawesome图标名称（可选）
    Archives:
      path: /archives/
      icon: fa-regular fa-box-archive # Fontawesome图标名称（可选）
    About Me:
      path: /page/about-me/
      icon: fa-regular fa-address-card # Fontawesome图标名称（可选）
